// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: tasks/task_message.proto

package tasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	generic "lms-task-service/pb/generic"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Task messages
type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	EndDate        string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Files          []*TaskFile            `protobuf:"bytes,10,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_tasks_task_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *Task) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *Task) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Task) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Task) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Task) GetFiles() []*TaskFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type TaskFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StorageId     string                 `protobuf:"bytes,5,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFile) Reset() {
	*x = TaskFile{}
	mi := &file_tasks_task_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFile) ProtoMessage() {}

func (x *TaskFile) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFile.ProtoReflect.Descriptor instead.
func (*TaskFile) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{1}
}

func (x *TaskFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskFile) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskFile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskFile) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *TaskFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TaskFile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TaskFile) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type TaskInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubjectClassId string                 `protobuf:"bytes,1,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	EndDate        string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Files          []*TaskFileInput       `protobuf:"bytes,6,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskInput) Reset() {
	*x = TaskInput{}
	mi := &file_tasks_task_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskInput) ProtoMessage() {}

func (x *TaskInput) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskInput.ProtoReflect.Descriptor instead.
func (*TaskInput) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{2}
}

func (x *TaskInput) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *TaskInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskInput) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *TaskInput) GetFiles() []*TaskFileInput {
	if x != nil {
		return x.Files
	}
	return nil
}

type TaskFileInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StorageId     string                 `protobuf:"bytes,3,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskFileInput) Reset() {
	*x = TaskFileInput{}
	mi := &file_tasks_task_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskFileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskFileInput) ProtoMessage() {}

func (x *TaskFileInput) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskFileInput.ProtoReflect.Descriptor instead.
func (*TaskFileInput) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{3}
}

func (x *TaskFileInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskFileInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskFileInput) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

type TaskUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubjectClassId string                 `protobuf:"bytes,2,opt,name=subject_class_id,json=subjectClassId,proto3" json:"subject_class_id,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	EndDate        string                 `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskUpdate) Reset() {
	*x = TaskUpdate{}
	mi := &file_tasks_task_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdate) ProtoMessage() {}

func (x *TaskUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdate.ProtoReflect.Descriptor instead.
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{4}
}

func (x *TaskUpdate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TaskUpdate) GetSubjectClassId() string {
	if x != nil {
		return x.SubjectClassId
	}
	return ""
}

func (x *TaskUpdate) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *TaskUpdate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskUpdate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskUpdate) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

// Student Task messages
type StudentTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StudentId     string                 `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Answer        string                 `protobuf:"bytes,4,opt,name=answer,proto3" json:"answer,omitempty"`
	Score         int32                  `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	Feedback      string                 `protobuf:"bytes,6,opt,name=feedback,proto3" json:"feedback,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Files         []*StudentTaskFile     `protobuf:"bytes,8,rep,name=files,proto3" json:"files,omitempty"`
	FeedbackFiles []*FeedbackFile        `protobuf:"bytes,9,rep,name=feedback_files,json=feedbackFiles,proto3" json:"feedback_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentTask) Reset() {
	*x = StudentTask{}
	mi := &file_tasks_task_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentTask) ProtoMessage() {}

func (x *StudentTask) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentTask.ProtoReflect.Descriptor instead.
func (*StudentTask) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{5}
}

func (x *StudentTask) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudentTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StudentTask) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentTask) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *StudentTask) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StudentTask) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *StudentTask) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StudentTask) GetFiles() []*StudentTaskFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *StudentTask) GetFeedbackFiles() []*FeedbackFile {
	if x != nil {
		return x.FeedbackFiles
	}
	return nil
}

type StudentTaskFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentTaskId string                 `protobuf:"bytes,2,opt,name=student_task_id,json=studentTaskId,proto3" json:"student_task_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	FileType      string                 `protobuf:"bytes,5,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	StorageId     string                 `protobuf:"bytes,6,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,10,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentTaskFile) Reset() {
	*x = StudentTaskFile{}
	mi := &file_tasks_task_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentTaskFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentTaskFile) ProtoMessage() {}

func (x *StudentTaskFile) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentTaskFile.ProtoReflect.Descriptor instead.
func (*StudentTaskFile) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{6}
}

func (x *StudentTaskFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StudentTaskFile) GetStudentTaskId() string {
	if x != nil {
		return x.StudentTaskId
	}
	return ""
}

func (x *StudentTaskFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentTaskFile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StudentTaskFile) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *StudentTaskFile) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *StudentTaskFile) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *StudentTaskFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StudentTaskFile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *StudentTaskFile) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type FeedbackFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentTaskId string                 `protobuf:"bytes,2,opt,name=student_task_id,json=studentTaskId,proto3" json:"student_task_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StorageId     string                 `protobuf:"bytes,5,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackFile) Reset() {
	*x = FeedbackFile{}
	mi := &file_tasks_task_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackFile) ProtoMessage() {}

func (x *FeedbackFile) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackFile.ProtoReflect.Descriptor instead.
func (*FeedbackFile) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{7}
}

func (x *FeedbackFile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FeedbackFile) GetStudentTaskId() string {
	if x != nil {
		return x.StudentTaskId
	}
	return ""
}

func (x *FeedbackFile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedbackFile) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeedbackFile) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *FeedbackFile) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FeedbackFile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *FeedbackFile) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type StudentTaskInput struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	TaskId        string                  `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	StudentId     string                  `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Answer        string                  `protobuf:"bytes,3,opt,name=answer,proto3" json:"answer,omitempty"`
	Files         []*StudentTaskFileInput `protobuf:"bytes,4,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentTaskInput) Reset() {
	*x = StudentTaskInput{}
	mi := &file_tasks_task_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentTaskInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentTaskInput) ProtoMessage() {}

func (x *StudentTaskInput) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentTaskInput.ProtoReflect.Descriptor instead.
func (*StudentTaskInput) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{8}
}

func (x *StudentTaskInput) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StudentTaskInput) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentTaskInput) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *StudentTaskInput) GetFiles() []*StudentTaskFileInput {
	if x != nil {
		return x.Files
	}
	return nil
}

type StudentTaskFileInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	StorageId     string                 `protobuf:"bytes,4,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentTaskFileInput) Reset() {
	*x = StudentTaskFileInput{}
	mi := &file_tasks_task_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentTaskFileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentTaskFileInput) ProtoMessage() {}

func (x *StudentTaskFileInput) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentTaskFileInput.ProtoReflect.Descriptor instead.
func (*StudentTaskFileInput) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{9}
}

func (x *StudentTaskFileInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentTaskFileInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StudentTaskFileInput) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *StudentTaskFileInput) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

func (x *StudentTaskFileInput) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type GradeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentTaskId string                 `protobuf:"bytes,1,opt,name=student_task_id,json=studentTaskId,proto3" json:"student_task_id,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Feedback      string                 `protobuf:"bytes,3,opt,name=feedback,proto3" json:"feedback,omitempty"`
	FeedbackFiles []*FeedbackFileInput   `protobuf:"bytes,4,rep,name=feedback_files,json=feedbackFiles,proto3" json:"feedback_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeInput) Reset() {
	*x = GradeInput{}
	mi := &file_tasks_task_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeInput) ProtoMessage() {}

func (x *GradeInput) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeInput.ProtoReflect.Descriptor instead.
func (*GradeInput) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{10}
}

func (x *GradeInput) GetStudentTaskId() string {
	if x != nil {
		return x.StudentTaskId
	}
	return ""
}

func (x *GradeInput) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GradeInput) GetFeedback() string {
	if x != nil {
		return x.Feedback
	}
	return ""
}

func (x *GradeInput) GetFeedbackFiles() []*FeedbackFileInput {
	if x != nil {
		return x.FeedbackFiles
	}
	return nil
}

type FeedbackFileInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	StorageId     string                 `protobuf:"bytes,3,opt,name=storage_id,json=storageId,proto3" json:"storage_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackFileInput) Reset() {
	*x = FeedbackFileInput{}
	mi := &file_tasks_task_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackFileInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackFileInput) ProtoMessage() {}

func (x *FeedbackFileInput) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackFileInput.ProtoReflect.Descriptor instead.
func (*FeedbackFileInput) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{11}
}

func (x *FeedbackFileInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeedbackFileInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeedbackFileInput) GetStorageId() string {
	if x != nil {
		return x.StorageId
	}
	return ""
}

type StudentTaskList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentTasks  []*StudentTask         `protobuf:"bytes,1,rep,name=student_tasks,json=studentTasks,proto3" json:"student_tasks,omitempty"`
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentTaskList) Reset() {
	*x = StudentTaskList{}
	mi := &file_tasks_task_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentTaskList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentTaskList) ProtoMessage() {}

func (x *StudentTaskList) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentTaskList.ProtoReflect.Descriptor instead.
func (*StudentTaskList) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{12}
}

func (x *StudentTaskList) GetStudentTasks() []*StudentTask {
	if x != nil {
		return x.StudentTasks
	}
	return nil
}

func (x *StudentTaskList) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type StudentTaskListInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagination    *generic.Pagination    `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentTaskListInput) Reset() {
	*x = StudentTaskListInput{}
	mi := &file_tasks_task_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentTaskListInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentTaskListInput) ProtoMessage() {}

func (x *StudentTaskListInput) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_task_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentTaskListInput.ProtoReflect.Descriptor instead.
func (*StudentTaskListInput) Descriptor() ([]byte, []int) {
	return file_tasks_task_message_proto_rawDescGZIP(), []int{13}
}

func (x *StudentTaskListInput) GetPagination() *generic.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *StudentTaskListInput) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_tasks_task_message_proto protoreflect.FileDescriptor

const file_tasks_task_message_proto_rawDesc = "" +
	"\n" +
	"\x18tasks/task_message.proto\x12\x05tasks\x1a\x1dgeneric/generic_message.proto\"\xa9\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\x12%\n" +
	"\x05files\x18\n" +
	" \x03(\v2\x0f.tasks.TaskFileR\x05files\"\xe5\x01\n" +
	"\bTaskFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x05 \x01(\tR\tstorageId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\"\xc6\x01\n" +
	"\tTaskInput\x12(\n" +
	"\x10subject_class_id\x18\x01 \x01(\tR\x0esubjectClassId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12*\n" +
	"\x05files\x18\x06 \x03(\v2\x14.tasks.TaskFileInputR\x05files\"d\n" +
	"\rTaskFileInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x03 \x01(\tR\tstorageId\"\xab\x01\n" +
	"\n" +
	"TaskUpdate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x10subject_class_id\x18\x02 \x01(\tR\x0esubjectClassId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\tR\aendDate\"\xa8\x02\n" +
	"\vStudentTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x16\n" +
	"\x06answer\x18\x04 \x01(\tR\x06answer\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x05R\x05score\x12\x1a\n" +
	"\bfeedback\x18\x06 \x01(\tR\bfeedback\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12,\n" +
	"\x05files\x18\b \x03(\v2\x16.tasks.StudentTaskFileR\x05files\x12:\n" +
	"\x0efeedback_files\x18\t \x03(\v2\x13.tasks.FeedbackFileR\rfeedbackFiles\"\xb0\x02\n" +
	"\x0fStudentTaskFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fstudent_task_id\x18\x02 \x01(\tR\rstudentTaskId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_type\x18\x05 \x01(\tR\bfileType\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x06 \x01(\tR\tstorageId\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\n" +
	" \x01(\tR\tupdatedBy\"\xf8\x01\n" +
	"\fFeedbackFile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x0fstudent_task_id\x18\x02 \x01(\tR\rstudentTaskId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x05 \x01(\tR\tstorageId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\b \x01(\tR\tupdatedBy\"\x95\x01\n" +
	"\x10StudentTaskInput\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x16\n" +
	"\x06answer\x18\x03 \x01(\tR\x06answer\x121\n" +
	"\x05files\x18\x04 \x03(\v2\x1b.tasks.StudentTaskFileInputR\x05files\"\xa0\x01\n" +
	"\x14StudentTaskFileInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x04 \x01(\tR\tstorageId\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\xa7\x01\n" +
	"\n" +
	"GradeInput\x12&\n" +
	"\x0fstudent_task_id\x18\x01 \x01(\tR\rstudentTaskId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x1a\n" +
	"\bfeedback\x18\x03 \x01(\tR\bfeedback\x12?\n" +
	"\x0efeedback_files\x18\x04 \x03(\v2\x18.tasks.FeedbackFileInputR\rfeedbackFiles\"h\n" +
	"\x11FeedbackFileInput\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"storage_id\x18\x03 \x01(\tR\tstorageId\"`\n" +
	"\x0fStudentTaskList\x127\n" +
	"\rstudent_tasks\x18\x01 \x03(\v2\x12.tasks.StudentTaskR\fstudentTasks\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\"n\n" +
	"\x14StudentTaskListInput\x12=\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1d.lms_task_services.PaginationR\n" +
	"pagination\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId2\x8a\x03\n" +
	"\vTaskService\x12'\n" +
	"\x06Create\x12\x10.tasks.TaskInput\x1a\v.tasks.Task\x12)\n" +
	"\x03Get\x12\x15.lms_task_services.Id\x1a\v.tasks.Task\x12(\n" +
	"\x06Update\x12\x11.tasks.TaskUpdate\x1a\v.tasks.Task\x12?\n" +
	"\x06Delete\x12\x15.lms_task_services.Id\x1a\x1e.lms_task_services.BoolMessage\x12<\n" +
	"\rStudentSubmit\x12\x17.tasks.StudentTaskInput\x1a\x12.tasks.StudentTask\x125\n" +
	"\fTeacherGrade\x12\x11.tasks.GradeInput\x1a\x12.tasks.StudentTask\x12G\n" +
	"\x10ListStudentTasks\x12\x1b.tasks.StudentTaskListInput\x1a\x16.tasks.StudentTaskListB!Z\x1flms-task-service/pb/tasks;tasksb\x06proto3"

var (
	file_tasks_task_message_proto_rawDescOnce sync.Once
	file_tasks_task_message_proto_rawDescData []byte
)

func file_tasks_task_message_proto_rawDescGZIP() []byte {
	file_tasks_task_message_proto_rawDescOnce.Do(func() {
		file_tasks_task_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_task_message_proto_rawDesc), len(file_tasks_task_message_proto_rawDesc)))
	})
	return file_tasks_task_message_proto_rawDescData
}

var file_tasks_task_message_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tasks_task_message_proto_goTypes = []any{
	(*Task)(nil),                 // 0: tasks.Task
	(*TaskFile)(nil),             // 1: tasks.TaskFile
	(*TaskInput)(nil),            // 2: tasks.TaskInput
	(*TaskFileInput)(nil),        // 3: tasks.TaskFileInput
	(*TaskUpdate)(nil),           // 4: tasks.TaskUpdate
	(*StudentTask)(nil),          // 5: tasks.StudentTask
	(*StudentTaskFile)(nil),      // 6: tasks.StudentTaskFile
	(*FeedbackFile)(nil),         // 7: tasks.FeedbackFile
	(*StudentTaskInput)(nil),     // 8: tasks.StudentTaskInput
	(*StudentTaskFileInput)(nil), // 9: tasks.StudentTaskFileInput
	(*GradeInput)(nil),           // 10: tasks.GradeInput
	(*FeedbackFileInput)(nil),    // 11: tasks.FeedbackFileInput
	(*StudentTaskList)(nil),      // 12: tasks.StudentTaskList
	(*StudentTaskListInput)(nil), // 13: tasks.StudentTaskListInput
	(*generic.Pagination)(nil),   // 14: lms_task_services.Pagination
	(*generic.Id)(nil),           // 15: lms_task_services.Id
	(*generic.BoolMessage)(nil),  // 16: lms_task_services.BoolMessage
}
var file_tasks_task_message_proto_depIdxs = []int32{
	1,  // 0: tasks.Task.files:type_name -> tasks.TaskFile
	3,  // 1: tasks.TaskInput.files:type_name -> tasks.TaskFileInput
	6,  // 2: tasks.StudentTask.files:type_name -> tasks.StudentTaskFile
	7,  // 3: tasks.StudentTask.feedback_files:type_name -> tasks.FeedbackFile
	9,  // 4: tasks.StudentTaskInput.files:type_name -> tasks.StudentTaskFileInput
	11, // 5: tasks.GradeInput.feedback_files:type_name -> tasks.FeedbackFileInput
	5,  // 6: tasks.StudentTaskList.student_tasks:type_name -> tasks.StudentTask
	14, // 7: tasks.StudentTaskListInput.pagination:type_name -> lms_task_services.Pagination
	2,  // 8: tasks.TaskService.Create:input_type -> tasks.TaskInput
	15, // 9: tasks.TaskService.Get:input_type -> lms_task_services.Id
	4,  // 10: tasks.TaskService.Update:input_type -> tasks.TaskUpdate
	15, // 11: tasks.TaskService.Delete:input_type -> lms_task_services.Id
	8,  // 12: tasks.TaskService.StudentSubmit:input_type -> tasks.StudentTaskInput
	10, // 13: tasks.TaskService.TeacherGrade:input_type -> tasks.GradeInput
	13, // 14: tasks.TaskService.ListStudentTasks:input_type -> tasks.StudentTaskListInput
	0,  // 15: tasks.TaskService.Create:output_type -> tasks.Task
	0,  // 16: tasks.TaskService.Get:output_type -> tasks.Task
	0,  // 17: tasks.TaskService.Update:output_type -> tasks.Task
	16, // 18: tasks.TaskService.Delete:output_type -> lms_task_services.BoolMessage
	5,  // 19: tasks.TaskService.StudentSubmit:output_type -> tasks.StudentTask
	5,  // 20: tasks.TaskService.TeacherGrade:output_type -> tasks.StudentTask
	12, // 21: tasks.TaskService.ListStudentTasks:output_type -> tasks.StudentTaskList
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_tasks_task_message_proto_init() }
func file_tasks_task_message_proto_init() {
	if File_tasks_task_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_task_message_proto_rawDesc), len(file_tasks_task_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_task_message_proto_goTypes,
		DependencyIndexes: file_tasks_task_message_proto_depIdxs,
		MessageInfos:      file_tasks_task_message_proto_msgTypes,
	}.Build()
	File_tasks_task_message_proto = out.File
	file_tasks_task_message_proto_goTypes = nil
	file_tasks_task_message_proto_depIdxs = nil
}
