// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: tasks/task_message.proto

package tasks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	generic "lms-task-service/pb/generic"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskService_Create_FullMethodName           = "/tasks.TaskService/Create"
	TaskService_Get_FullMethodName              = "/tasks.TaskService/Get"
	TaskService_Update_FullMethodName           = "/tasks.TaskService/Update"
	TaskService_Delete_FullMethodName           = "/tasks.TaskService/Delete"
	TaskService_StudentSubmit_FullMethodName    = "/tasks.TaskService/StudentSubmit"
	TaskService_TeacherGrade_FullMethodName     = "/tasks.TaskService/TeacherGrade"
	TaskService_ListStudentTasks_FullMethodName = "/tasks.TaskService/ListStudentTasks"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Task Service
type TaskServiceClient interface {
	Create(ctx context.Context, in *TaskInput, opts ...grpc.CallOption) (*Task, error)
	Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*Task, error)
	Update(ctx context.Context, in *TaskUpdate, opts ...grpc.CallOption) (*Task, error)
	Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error)
	StudentSubmit(ctx context.Context, in *StudentTaskInput, opts ...grpc.CallOption) (*StudentTask, error)
	TeacherGrade(ctx context.Context, in *GradeInput, opts ...grpc.CallOption) (*StudentTask, error)
	ListStudentTasks(ctx context.Context, in *StudentTaskListInput, opts ...grpc.CallOption) (*StudentTaskList, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) Create(ctx context.Context, in *TaskInput, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Get(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Update(ctx context.Context, in *TaskUpdate, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Delete(ctx context.Context, in *generic.Id, opts ...grpc.CallOption) (*generic.BoolMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(generic.BoolMessage)
	err := c.cc.Invoke(ctx, TaskService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) StudentSubmit(ctx context.Context, in *StudentTaskInput, opts ...grpc.CallOption) (*StudentTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentTask)
	err := c.cc.Invoke(ctx, TaskService_StudentSubmit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) TeacherGrade(ctx context.Context, in *GradeInput, opts ...grpc.CallOption) (*StudentTask, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentTask)
	err := c.cc.Invoke(ctx, TaskService_TeacherGrade_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListStudentTasks(ctx context.Context, in *StudentTaskListInput, opts ...grpc.CallOption) (*StudentTaskList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StudentTaskList)
	err := c.cc.Invoke(ctx, TaskService_ListStudentTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations should embed UnimplementedTaskServiceServer
// for forward compatibility.
//
// Task Service
type TaskServiceServer interface {
	Create(context.Context, *TaskInput) (*Task, error)
	Get(context.Context, *generic.Id) (*Task, error)
	Update(context.Context, *TaskUpdate) (*Task, error)
	Delete(context.Context, *generic.Id) (*generic.BoolMessage, error)
	StudentSubmit(context.Context, *StudentTaskInput) (*StudentTask, error)
	TeacherGrade(context.Context, *GradeInput) (*StudentTask, error)
	ListStudentTasks(context.Context, *StudentTaskListInput) (*StudentTaskList, error)
}

// UnimplementedTaskServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskServiceServer struct{}

func (UnimplementedTaskServiceServer) Create(context.Context, *TaskInput) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedTaskServiceServer) Get(context.Context, *generic.Id) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedTaskServiceServer) Update(context.Context, *TaskUpdate) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedTaskServiceServer) Delete(context.Context, *generic.Id) (*generic.BoolMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedTaskServiceServer) StudentSubmit(context.Context, *StudentTaskInput) (*StudentTask, error) {
	return nil, status.Error(codes.Unimplemented, "method StudentSubmit not implemented")
}
func (UnimplementedTaskServiceServer) TeacherGrade(context.Context, *GradeInput) (*StudentTask, error) {
	return nil, status.Error(codes.Unimplemented, "method TeacherGrade not implemented")
}
func (UnimplementedTaskServiceServer) ListStudentTasks(context.Context, *StudentTaskListInput) (*StudentTaskList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStudentTasks not implemented")
}
func (UnimplementedTaskServiceServer) testEmbeddedByValue() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Create(ctx, req.(*TaskInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Get(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskUpdate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Update(ctx, req.(*TaskUpdate))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(generic.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).Delete(ctx, req.(*generic.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_StudentSubmit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentTaskInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).StudentSubmit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_StudentSubmit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).StudentSubmit(ctx, req.(*StudentTaskInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_TeacherGrade_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GradeInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).TeacherGrade(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_TeacherGrade_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).TeacherGrade(ctx, req.(*GradeInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListStudentTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentTaskListInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).ListStudentTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_ListStudentTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).ListStudentTasks(ctx, req.(*StudentTaskListInput))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tasks.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _TaskService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _TaskService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _TaskService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _TaskService_Delete_Handler,
		},
		{
			MethodName: "StudentSubmit",
			Handler:    _TaskService_StudentSubmit_Handler,
		},
		{
			MethodName: "TeacherGrade",
			Handler:    _TaskService_TeacherGrade_Handler,
		},
		{
			MethodName: "ListStudentTasks",
			Handler:    _TaskService_ListStudentTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tasks/task_message.proto",
}
